# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Early warning system' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  
  pod 'Eureka'
  pod 'SVProgressHUD'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  # Pods for Early warning system

  target 'Early warning systemTests' do
    inherit! :search_paths
    
    # Pods for testing
  end

end
